# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
email: laisililai@live.cn


title:
  en: Lesley Lai
  zh: 赖思理
subtitle:
  en: Video game fanatic
  zh: 游戏狂热爱好者
description:
  en: Hello, I am Lesley Lai.
  zh: 大家好，我是赖思理。
lang_name:
  en: English
  zh: 中文
index:
  en: 
  zh: index_zh.html
about:
  en: About
  zh: 关于
feed:
  en: /feed_en.xml
  zh: /feed_zh.xml
wiki:
  en: Wiki
  zh: 我的维基
home:
  en: Home 
  zh: 主页
src_info:
  en: This blog is built using <a href="http://jekyllrb.com/">jekyll</a>. 
  zh: 这个博客是使用<a href="http://jekyllrb.com/">jekyll</a>搭建的。
source_code:
  en: Source Code
  zh: 源代码
tags_name:
  en: Tags
  zh: 标签
archives:
  en: Archives
  zh: 分类


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lesleylai.info" # the base hostname & protocol for your site

# Custom variables:
disqus: "lesleylaiblog"
duoshuo: "lesleylaiblog"
github:
  repo: https://github.com/LesleyLai/blog


# Build settings
markdown: kramdown
destination: site

sass:
    sass_dir: /sass


# Outputting
permalink: /:categories/:year-:month/:title
